import type { Metadata } from "next";
import "./globals.css";
import { ApolloClientProvider } from "@/shared/providers/ApolloClientProvider";
import Header from "@/shared/components/Header/Header";
import { ToastProvider } from "@/shared/providers/ToastProvider";
import { StoreProvider } from "@/shared/providers/StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="ru">
      <body
        className="bg-[#0F0F0F]"
      >
        <ToastProvider />
        <StoreProvider>
        <ApolloClientProvider>
          {/* <ThemeProvider > */}
            <Header />
            {children}
            {/* </ThemeProvider> */}
        </ApolloClientProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
